CFLAGS=-Wall -g

all: ex1 ex2 ex7 variables_in_c ex8 ex9 ex10 ex10.1 ex10.3 ex11 ex12 ex13 ex14 ex15 testing_pointers p1 ex16 p2 p3 p4 p5 p6 ex17 p7

clean:
	rm -rf ex1
	rm -rf ex2
	rm -rf ex7
	rm -rf variables_in_c
	rm -rf ex8
	rm -rf ex9
	rm -rf ex10
	rm -rf ex10.1
	rm -rf ex10.3
	rm -rf ex11
	rm -rf ex12
	rm -rf ex13
	rm -rf ex14
	rm -rf ex15
	rm -rf testing_pointers
	rm -rf p1
	rm -rf ex16
	rm -rf p2
	rm -rf p3
	rm -rf p4
	rm -rf p5
	rm -rf p6
	rm -rf ex17
	rm -rf p7
